import { StyleSheet } from 'react-native';
import { colors, fonts } from '../constants/theme';

export const guideStyles = StyleSheet.create({
  root: {
    flex: 1,
  },
  mapCard: {
    marginHorizontal: 12,
    marginBottom: 12,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: colors.radius,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  card: {
    marginHorizontal: 12,
    marginBottom: 12,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: colors.radius,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: fonts.semiBold,
    color: colors.cardHeading,
    marginBottom: 8,
  },
  lead: {
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 19,
    color: colors.textMuted,
    marginTop: -2,
    marginBottom: 14,
  },
  leadStrong: {
    color: colors.accent,
    fontFamily: fonts.semiBold,
  },
  groupRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: -2,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  searchWrap: {
    marginBottom: 10,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 32,
  },
  item: {
    borderRadius: 9,
    backgroundColor: colors.itemBg,
    borderWidth: 1,
    borderColor: colors.itemBorder,
    overflow: 'hidden',
    marginHorizontal: 12,
    marginBottom: 6,
  },
  itemBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 11,
  },
  itemTitleRow: {
    flex: 1,
    gap: 6,
  },
  itemTitle: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colors.text,
  },
  itemTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  itemTag: {
    fontSize: 10,
    fontFamily: fonts.semiBold,
    color: colors.link,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(165, 243, 252, 0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  itemTagZone: {
    color: colors.accent,
    borderColor: 'rgba(251, 191, 36, 0.35)',
  },
  itemTagPickup: {
    color: '#fef3c7',
    borderColor: 'rgba(251, 191, 36, 0.5)',
    backgroundColor: 'rgba(180, 83, 9, 0.35)',
  },
  pickupBanner: {
    marginBottom: 12,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(180, 83, 9, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.35)',
  },
  pickupBannerTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#fef3c7',
    marginBottom: 4,
  },
  pickupBannerText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 17,
    color: 'rgba(254, 243, 199, 0.92)',
  },
  pickupNote: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 18,
    color: '#fde68a',
    paddingHorizontal: 11,
    paddingBottom: 10,
  },
  itemTagMealBreakfast: {
    color: '#d1fae5',
    borderColor: 'rgba(110, 231, 183, 0.45)',
    backgroundColor: 'rgba(5, 150, 105, 0.35)',
  },
  itemTagMealDinner: {
    color: '#e0e7ff',
    borderColor: 'rgba(165, 180, 252, 0.45)',
    backgroundColor: 'rgba(67, 56, 202, 0.35)',
  },
  mealBanner: {
    marginBottom: 12,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(5, 150, 105, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(110, 231, 183, 0.35)',
  },
  mealBannerTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#d1fae5',
    marginBottom: 4,
  },
  mealBannerText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 17,
    color: 'rgba(209, 250, 229, 0.92)',
  },
  mealNote: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 18,
    color: '#a7f3d0',
    paddingHorizontal: 11,
    paddingBottom: 10,
  },
  resortTag: {
    color: '#bfdbfe',
    borderColor: 'rgba(147, 197, 253, 0.5)',
    backgroundColor: 'rgba(26, 115, 232, 0.35)',
  },
  resortMealBlock: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 19,
    color: colors.textDesc,
    paddingHorizontal: 11,
    paddingBottom: 10,
  },
  resortMealLabel: {
    fontFamily: fonts.bold,
    color: colors.cardHeading,
  },
  resortBanner: {
    marginBottom: 12,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(26, 115, 232, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.35)',
  },
  resortBannerTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#bfdbfe',
    marginBottom: 4,
  },
  resortBannerText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 17,
    color: 'rgba(219, 234, 254, 0.92)',
  },
  resultCount: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.textMuted,
    marginBottom: 8,
  },
  chev: {
    fontSize: 10,
    color: colors.link,
  },
  itemDetail: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
    paddingTop: 8,
  },
  itemDesc: {
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 20,
    color: colors.textDesc,
    paddingHorizontal: 11,
    paddingBottom: 8,
  },
  itemActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 11,
    paddingBottom: 11,
  },
  itemLink: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: colors.link,
    textDecorationLine: 'underline',
  },
});
