import { StyleSheet } from 'react-native';
import { colors, fonts } from '../constants/theme';

export const guideStyles = StyleSheet.create({
  root: {
    flex: 1,
  },
  infoCard: {
    marginHorizontal: 12,
    marginBottom: 8,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: colors.radius,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  filterCard: {
    marginHorizontal: 12,
    marginBottom: 12,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: colors.radius,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 16,
  },
  mapSection: {
    marginHorizontal: 12,
    marginBottom: 10,
  },
  resortDetailSection: {
    marginTop: 10,
    borderRadius: 9,
    backgroundColor: colors.itemBg,
    borderWidth: 1,
    borderColor: 'rgba(26, 115, 232, 0.45)',
    overflow: 'hidden',
  },
  resortDetailHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: 'rgba(26, 115, 232, 0.22)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(147, 197, 253, 0.25)',
  },
  resortDetailTitle: {
    fontSize: 15,
    fontFamily: fonts.semiBold,
    color: '#dbeafe',
    marginBottom: 4,
  },
  resortDetailZone: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: 'rgba(219, 234, 254, 0.85)',
  },
  resortDetailBody: {
    paddingTop: 8,
  },
  restaurantDetailSection: {
    marginTop: 10,
    borderRadius: 9,
    backgroundColor: colors.itemBg,
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.4)',
    overflow: 'hidden',
  },
  restaurantDetailHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: 'rgba(15, 118, 110, 0.35)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(153, 246, 228, 0.2)',
  },
  restaurantDetailTitle: {
    fontSize: 15,
    fontFamily: fonts.semiBold,
    color: colors.cardHeading,
    marginBottom: 8,
  },
  restaurantDetailTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  restaurantDetailBody: {
    paddingTop: 4,
    paddingBottom: 4,
  },
  restaurantDetailLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 11,
    paddingBottom: 10,
  },
  resortBlogLinkWrap: {
    paddingHorizontal: 11,
    paddingBottom: 10,
  },
  resortReviewLinkWrap: {
    paddingHorizontal: 11,
    paddingBottom: 10,
    gap: 8,
  },
  resortReviewLinkBtn: {
    alignSelf: 'stretch',
    width: '100%',
  },
  resortBlogLinkBtn: {
    alignSelf: 'flex-start',
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(165, 243, 252, 0.32)',
    backgroundColor: 'rgba(11, 37, 46, 0.42)',
  },
  resortBlogLinkBtnPressed: {
    backgroundColor: 'rgba(165, 243, 252, 0.1)',
    borderColor: 'rgba(165, 243, 252, 0.48)',
  },
  resortBlogLinkText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: 'rgba(165, 243, 252, 0.9)',
    letterSpacing: -0.2,
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: fonts.semiBold,
    color: colors.cardHeading,
    marginBottom: 8,
  },
  lead: {
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 19,
    color: colors.textMuted,
    marginTop: -2,
    marginBottom: 0,
  },
  leadStrong: {
    color: colors.accent,
    fontFamily: fonts.semiBold,
  },
  groupRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: -2,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 32,
  },
  item: {
    borderRadius: 9,
    backgroundColor: colors.itemBg,
    borderWidth: 1,
    borderColor: colors.itemBorder,
    overflow: 'hidden',
    marginHorizontal: 12,
    marginBottom: 6,
  },
  itemSelected: {
    borderColor: 'rgba(26, 115, 232, 0.65)',
    backgroundColor: 'rgba(26, 115, 232, 0.12)',
  },
  itemSelectedRestaurant: {
    borderColor: 'rgba(45, 212, 191, 0.55)',
    backgroundColor: 'rgba(15, 118, 110, 0.18)',
  },
  itemSelectedNightMarket: {
    borderColor: 'rgba(167, 139, 250, 0.55)',
    backgroundColor: 'rgba(76, 29, 149, 0.22)',
  },
  nightMarketTag: {
    color: '#e9d5ff',
    borderColor: 'rgba(196, 181, 253, 0.45)',
    backgroundColor: 'rgba(76, 29, 149, 0.35)',
  },
  nightMarketDetailSection: {
    marginTop: 10,
    borderRadius: 9,
    backgroundColor: colors.itemBg,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.45)',
    overflow: 'hidden',
  },
  nightMarketDetailHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: 'rgba(76, 29, 149, 0.28)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(196, 181, 253, 0.25)',
  },
  nightMarketDetailTitle: {
    fontSize: 15,
    fontFamily: fonts.semiBold,
    color: '#ede9fe',
    marginBottom: 4,
  },
  nightMarketDetailSubtitle: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: 'rgba(221, 214, 254, 0.9)',
    marginBottom: 4,
  },
  nightMarketDetailZone: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: 'rgba(233, 213, 255, 0.88)',
  },
  nightMarketDetailBody: {
    paddingTop: 4,
  },
  nightMarketBanner: {
    marginBottom: 0,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(76, 29, 149, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(196, 181, 253, 0.35)',
  },
  nightMarketBannerTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#e9d5ff',
    marginBottom: 4,
  },
  nightMarketBannerText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 17,
    color: 'rgba(233, 213, 255, 0.92)',
  },
  nightMarketBannerHint: {
    marginTop: 8,
    color: 'rgba(233, 213, 255, 0.75)',
  },
  itemBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 11,
  },
  itemTitleRow: {
    flex: 1,
    gap: 6,
  },
  itemTitle: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colors.text,
  },
  itemTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  itemTag: {
    fontSize: 10,
    fontFamily: fonts.semiBold,
    color: colors.link,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(165, 243, 252, 0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  itemTagZone: {
    color: colors.accent,
    borderColor: 'rgba(251, 191, 36, 0.35)',
  },
  itemTagMenu: {
    color: '#bbf7d0',
    borderColor: 'rgba(134, 239, 172, 0.4)',
    backgroundColor: 'rgba(21, 128, 61, 0.3)',
  },
  itemTagCompanion: {
    color: '#fbcfe8',
    borderColor: 'rgba(244, 114, 182, 0.4)',
    backgroundColor: 'rgba(157, 23, 77, 0.28)',
  },
  itemTagPickup: {
    color: '#fef3c7',
    borderColor: 'rgba(251, 191, 36, 0.5)',
    backgroundColor: 'rgba(180, 83, 9, 0.35)',
  },
  itemTagPickupLast: {
    marginLeft: 'auto',
  },
  pickupBanner: {
    marginBottom: 0,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(180, 83, 9, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.35)',
  },
  pickupBannerTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#fef3c7',
    marginBottom: 4,
  },
  pickupBannerText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 17,
    color: 'rgba(254, 243, 199, 0.92)',
  },
  pickupNote: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 18,
    color: '#fde68a',
    paddingHorizontal: 11,
    paddingTop: 4,
    paddingBottom: 10,
  },
  itemTagMealBreakfast: {
    color: '#d1fae5',
    borderColor: 'rgba(110, 231, 183, 0.45)',
    backgroundColor: 'rgba(5, 150, 105, 0.35)',
  },
  itemTagMealDinner: {
    color: '#e0e7ff',
    borderColor: 'rgba(165, 180, 252, 0.45)',
    backgroundColor: 'rgba(67, 56, 202, 0.35)',
  },
  mealBanner: {
    marginBottom: 0,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(5, 150, 105, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(110, 231, 183, 0.35)',
  },
  mealBannerTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#d1fae5',
    marginBottom: 4,
  },
  mealBannerText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 17,
    color: 'rgba(209, 250, 229, 0.92)',
  },
  mealNote: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 18,
    color: '#a7f3d0',
    paddingHorizontal: 11,
    paddingBottom: 10,
  },
  resortTag: {
    color: '#bfdbfe',
    borderColor: 'rgba(147, 197, 253, 0.5)',
    backgroundColor: 'rgba(26, 115, 232, 0.35)',
  },
  resortMealBlock: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 19,
    color: colors.textDesc,
    paddingHorizontal: 11,
    paddingBottom: 10,
  },
  resortMealLabel: {
    fontFamily: fonts.bold,
    color: colors.cardHeading,
  },
  resortOtherBlock: {
    paddingHorizontal: 11,
    paddingBottom: 12,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
  },
  resortOtherTitle: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: '#bfdbfe',
    marginBottom: 8,
  },
  resortOtherItem: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 18,
    color: colors.textDesc,
    marginBottom: 6,
  },
  resortOtherName: {
    fontFamily: fonts.semiBold,
    color: '#a5f3fc',
  },
  resortBanner: {
    marginBottom: 0,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(26, 115, 232, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.35)',
  },
  resortBannerTitle: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#bfdbfe',
    marginBottom: 4,
  },
  resortBannerText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 17,
    color: 'rgba(219, 234, 254, 0.92)',
  },
  resultCount: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.textMuted,
    marginBottom: 8,
  },
  chev: {
    fontSize: 10,
    color: colors.link,
  },
  itemDetail: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
    paddingTop: 8,
  },
  itemDesc: {
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 20,
    color: colors.textDesc,
    paddingHorizontal: 11,
    paddingBottom: 8,
  },
  itemActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 11,
    paddingBottom: 11,
  },
  itemLink: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: colors.link,
    textDecorationLine: 'underline',
  },
});
